#ifndef PANKEY_BASE_VERSION_HPP
	#define PANKEY_BASE_VERSION_HPP

	#define PANKEY_BASE_VERSION_MAJOR 1
	#define PANKEY_BASE_VERSION_MINOR 0
	#define PANKEY_BASE_VERSION_PATCH 0
	#define PANKEY_BASE_VERSION "1.0.0"

	#define IS_PANKEY_BASE_VERSION(MA,MI,P) \
		((PANKEY_BASE_VERSION_MAJOR == (MA)) && \
		(PANKEY_BASE_VERSION_MINOR == (MI)) && \
		(PANKEY_BASE_VERSION_PATCH == (P)))

	#define IS_PANKEY_BASE_VERSION_AT_LEAST(MA,MI,P) \
		((PANKEY_BASE_VERSION_MAJOR > (MA)) || \
		((PANKEY_BASE_VERSION_MAJOR == (MA)) && (PANKEY_BASE_VERSION_MINOR > (MI))) || \
		((PANKEY_BASE_VERSION_MAJOR == (MA)) && (PANKEY_BASE_VERSION_MINOR == (MI)) && (PANKEY_BASE_VERSION_PATCH >= (P))))
	
	#define IS_PANKEY_BASE_VERSION_BEFORE(MA,MI,P) \
		((PANKEY_BASE_VERSION_MAJOR < (MA)) || \
		((PANKEY_BASE_VERSION_MAJOR == (MA)) && (PANKEY_BASE_VERSION_MINOR < (MI))) || \
		((PANKEY_BASE_VERSION_MAJOR == (MA)) && (PANKEY_BASE_VERSION_MINOR == (MI)) && (PANKEY_BASE_VERSION_PATCH < (P))))

#endif
